# -*- coding: utf-8 -*-
"""final project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1icnEOXoLWrOTR-lGwp4cBnQDEygt0BAk
"""

import random
import sys
import time
import requests
from bs4 import BeautifulSoup

def create_invitation(name):
    content = f"您好{name}：\n您被邀請參加魷魚遊戲！贏者將獨得456億獎金！\n\n請告訴我們您是否願意參加遊戲。"
    with open("invitation.txt", "w") as file:
        file.write(content)

def participate_game():
    choice = input("您是否願意參加遊戲？（yes/no）：")
    while choice.lower() not in ["yes", "no", "y", "n"]:
        choice = input("無效的輸入，請重新輸入（yes/no）：")
    if choice.lower() in ["yes", "y"]:
        player_code = random.randint(1, 456)
        print(f"您的參賽編碼是：{player_code}")
        print("遊戲開始！")
        return True
    else:
        print("感謝您的考慮。有機會再見！")
        return False

def game_one():
    print("第一關開始!")
    if participate_game():
        print("遊戲規則很簡單：當木頭人背對著您並說出「一、二、三 木頭人」時，您可以前進。")
        print("但是，當木頭人轉身時，若您移動就會被淘汰。")
        print("您有5分鐘的時間抵達終點線，如果您未能在限時內抵達，將會被淘汰。")
        print("讓我們開始遊戲吧！")

        move_count = 0
        start_time = time.time()
        end_time = start_time + 300  # 5分鐘
        required_moves = 3  #可以在這邊給變數，後面移動到第三步就會遊戲1就會結束了

        while time.time() < end_time:
            print("木頭人：「一、二、三 木頭人」")
            move = input("請輸入「1」表示前進，「2」表示原地不動：")

            if move == "1":
                doll_direction = random.choice(["背對", "面對"])

                if doll_direction == "面對":
                    print("木頭人轉身了！您被發現了！淘汰！")
                    print(f"很遺憾，您未能通過第一關。")
                    return False

                print("您往前移動了。")
                move_count += 1

                if move_count == required_moves:
                    return True

            elif move == "2":
                print("您原地不動。")

                if move_count == required_moves:
                    return True

            else:
                print("無效的輸入，請重新輸入。")
                continue

            reply_delay = random.randint(3, 5)
            time.sleep(reply_delay)
        print("時間到！您未能在限時內抵達終點線，您被淘汰了！")
        print(f"很遺憾，您未能通過第一關。")
        return False

import random
import requests
from bs4 import BeautifulSoup

def get_random_number_from_website():
    response = requests.get('https://www.math-only-math.com/Whole-Numbers.html')
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        number_elements = soup.find_all('li')
        if number_elements:
            random_number = random.choice(number_elements).text
            return random_number
    return None

def game_two():
    secret_number = random.randint(1, 100)
    attempts = 0

    while True:
        guess = input("請猜一個介於1和100之間的數字：")

        if not guess.isdigit():
            print("請輸入有效的數字！")
            continue

        guess = int(guess)
        attempts += 1

        if guess < secret_number:
            print("太小了！再試一次。")
        elif guess > secret_number:
            print("太大了！再試一次。")
        else:
            print(f"恭喜！您猜中了答案，共使用了{attempts}次。您將繼續進行下一關")
            return True

        if attempts >= 5:
            print("猜測次數已達上限，您被淘汰了！")
            print("很遺憾，您未能通過第二關")
            return False

# 運行遊戲
#game_two()   這邊你呼叫了game2，所以才先跑game2，建議主程式都寫在最下面
import random
import time

def game_three():
    print("歡迎來到第三關：「椪糖」")
    print("在遊戲開始前，請在圓形、三角形、星星、雨傘四種圖案中選擇一種。")
    print("您將會拿到選定圖案的椪糖形狀，並有十分鐘的時間用細針將椪糖分離出指定形狀。")
    print("讓我們開始遊戲吧！")

    shapes = ["圓形", "三角形", "星星", "雨傘"]
    selected_shape = None

    while selected_shape is None:
        shape_input = input("請輸入選擇的形狀代號（1:圓形 2:三角形 3:星星 4:雨傘）：")
        if shape_input.isdigit():
            shape_index = int(shape_input) - 1
            if 0 <= shape_index < len(shapes):
                selected_shape = shapes[shape_index]
            else:
                print("無效的選擇，請重新選擇。")
        else:
            print("無效的選擇，請重新選擇。")

    print(f"您選擇了 {selected_shape} 形狀。")

    total = 0

    for i in range(5):
        print(f"請問您在第 {i+1} 次時，要如何分離椪糖呢？")
        print("1: 滴汗融化/2: 針戳圖案/3: 舌頭舔舐")

        valid_choice = False
        while not valid_choice:
            method_input = input("請輸入選擇方式：")

            if method_input == "1":
                total += 3
                valid_choice = True
            elif method_input == "2":
                total += random.randint(1, 2)
                valid_choice = True
            elif method_input == "3":
                total += int(method_input)
                valid_choice = True
            else:
                print("無效的選擇，請重新選擇。")

        reply_delay = random.randint(0, 5)
        time.sleep(reply_delay)

    if total % 2 == 0:
        print("很抱歉，遊戲失敗！您被淘汰了！")
        return False
    else:
        print("恭喜！通關成功！")
        return True

def game_four():
    choices = {
        "1": "剪刀",
        "2": "石頭",
        "3": "布"
    }

    player1_wins = 0
    player2_wins = 0

    while player1_wins < 3 and player2_wins < 3:
        print("==============")
        print("玩家1 VS 玩家2")
        print("==============")

        player1_choice = input("玩家1，請選擇 1（剪刀）、2（石頭）或 3（布）：")

        if player1_choice not in choices:
            print("請輸入有效的選擇！")
            continue

        player2_choice = str(random.randint(1, 3))
        time.sleep(2)  # 等待2秒模擬玩家2的反應

        print(f"玩家1選擇了 {choices[player1_choice]}，玩家2選擇了 {choices[player2_choice]}。")

        if (
            (player1_choice == "1" and player2_choice == "3")
            or (player1_choice == "2" and player2_choice == "1")
            or (player1_choice == "3" and player2_choice == "2")
        ):
            print("玩家1獲得本局勝利！")
            player1_wins += 1
        elif (
            (player2_choice == "1" and player1_choice == "3")
            or (player2_choice == "2" and player1_choice == "1")
            or (player2_choice == "3" and player1_choice == "2")
        ):
            print("玩家2獲得本局勝利！")
            player2_wins += 1
        else:
            print("本局平局！")

        print(f"目前比分：玩家1 {player1_wins} - {player2_wins} 玩家2")
        print("======================")

    if player1_wins > player2_wins:
        print("恭喜玩家1勝利！成功通過本關！")
        return True
    else:
        print("很遺憾，玩家1未能獲勝，您被淘汰了！")
        return False

def game_five():
    player1_beads = 5
    player1_hits = 0
    player2_beads = 5
    player2_hits = 0

    print("歡迎來到打彈珠遊戲！")
    print("遊戲規則：每個玩家有5顆彈珠，輪流進行彈珠動作，擊中指定地點即可獲勝，或在指定區域剩下的彈珠多則獲勝。")
    print("您將代表玩家1出戰，玩家2由其他生存者代表。")

    for round in range(1, 6):
        print(f"第 {round} 回合開始")

        print("現在輪到玩家1")
        input("按下 Enter 鍵彈出彈珠...")
        result = random.randint(1, 2)  # 隨機生成1或2

        if result == 1:
            print("玩家1成功擊中指定地點！")
            player1_beads -= 1
            player1_hits += 1
        else:
            print("玩家1未擊中指定地點...")

        print("現在輪到玩家2")
        print("玩家2彈珠彈出中...")
        time.sleep(3)  # 延遲3秒
        result = random.randint(1, 2)

        if result == 1:
            print("玩家2成功擊中指定地點！")
            player2_beads -= 1
            player2_hits += 1
        else:
            print("玩家2未擊中指定地點...")

    if player1_beads > player2_beads and player1_hits > player2_hits:
        print("玩家1獲勝！進入下一個遊戲。")
        return True
    else:
        print("玩家1失敗，您將被淘汰，遊戲結束！")
        return False
def main():
    print("歡迎來到魷魚遊戲！")

    if game_one():   #這邊你沒有在func裡寫要輸入什麼字，不需要輸入，這邊是要輸入
        print("恭喜！您通過了第一關")

        if game_two():
            print("恭喜！您通過了第二關")

            if game_three():
                print("恭喜！您通過了第三關")

                if game_four():
                    print("恭喜！您通過了第四關")

                    if game_five():
                        print("恭喜！您成功通過全部關卡，成為遊戲最後勝利的玩家！您將獲得456億元的獎金！")
                        
        print("遊戲結束！感謝參與遊戲，期待未來再見！")
main()